# Generated by Django 3.0.8 on 2021-02-11 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('exchange', models.CharField(choices=[('NDAQ', 'NASDAQ'), ('OSEBX', 'Oslo stock exchange')], default='None', max_length=200)),
                ('ticker', models.CharField(default='None', max_length=10)),
                ('rating', models.CharField(choices=[('1', 'Excellent'), ('2', 'Very good'), ('3', 'Good'), ('4', 'Poor'), ('5', 'Very poor')], default='None', max_length=50)),
                ('stock_momentum', models.CharField(choices=[('1', 'Excellent performing stock'), ('2', 'Strong performing stock'), ('3', 'Average performing stock'), ('4', 'Slow performing stock'), ('5', 'Poor performing stock')], default='None', max_length=50)),
                ('investment_type', models.CharField(choices=[('1', 'Growth stock investment'), ('2', 'Value stock investment'), ('3', 'Trading investment'), ('4', 'Day trade investment')], default='None', max_length=50)),
                ('investment_status', models.CharField(choices=[('1', 'Good standing'), ('2', 'Watch closely'), ('3', 'Needs to be replaced')], default='None', max_length=50)),
                ('investment_decision', models.CharField(choices=[('1', 'Invested'), ('2', 'Approved'), ('3', 'On watchlist'), ('4', 'Rejected')], default='None', max_length=50)),
                ('tech_analysis_opinion', models.CharField(choices=[('1', 'Good entry at this time'), ('2', 'Might be good entry soon'), ('3', 'Not a good entry at this time')], default='None', max_length=50)),
                ('fundamental_analysis_opinion', models.CharField(choices=[('1', 'Excellent fundamentals'), ('2', 'Good fundamentals'), ('3', 'Average fundamentals'), ('4', 'Terrible fundamentals')], default='None', max_length=50)),
                ('entry_strategy', models.CharField(default='No strategy defined', max_length=250)),
                ('exit_strategy', models.CharField(default='No strategy defined', max_length=250)),
                ('general_notes', models.CharField(blank=True, default='', max_length=250)),
                ('shared', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_transaction', models.CharField(choices=[('1', 'Stock purchase'), ('2', 'Stock sold'), ('3', 'Dividend payout'), ('4', 'Tax payout'), ('5', 'Tax payment'), ('6', 'Interest payment'), ('7', 'Interest payout')], max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('date_of_transaction', models.DateField()),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv_profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('part_of_revenue', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv_profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('rating', models.CharField(choices=[('1', 'High impact'), ('2', 'Medium impact'), ('3', 'Low impact')], max_length=250)),
                ('notes', models.CharField(max_length=250)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv_profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueIncomeSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_source', models.CharField(choices=[('1', 'Revenue'), ('2', 'Income')], max_length=250)),
                ('source_frequency', models.CharField(choices=[('1', 'Recurring'), ('2', 'One-time')], max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv_profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('report_type', models.CharField(choices=[('1', 'Earnings report - quarterly'), ('2', 'Earnings report - annual'), ('3', 'Sales report'), ('4', 'Traffic report'), ('5', 'Other')], max_length=150)),
                ('link', models.URLField()),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv_profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.CharField(max_length=250)),
                ('significance', models.CharField(choices=[('1', 'News of high interest'), ('2', 'News of medium interest'), ('3', 'News of low interest')], max_length=100)),
                ('link', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='KeyMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('type_of_metric', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=500)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv_profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('competitor_impact', models.CharField(choices=[('1', 'Biggest competitor'), ('2', 'Medium competitor'), ('3', 'Small competitor')], max_length=50)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv_profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('broker', models.CharField(max_length=250)),
                ('analyst', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv_profiles.Profile')),
            ],
        ),
    ]
