# Generated by Django 3.0.8 on 2021-03-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentidea',
            name='recommendations',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
